// GENERATED by scripts/build-theme-packs.mjs — do not edit.
//
// A Helex extension pack: TEHIK's Andmekirjelduskeskkond — the Estonian health-data description environment.
//
// Loaded by the shell before first render via APP_BOOTSTRAP_MODULES (SHELL.11 R8). It imports
// nothing — a pack that imported @helex/ui would bundle a second React and antd, and two Reacts
// break hooks — and instead reads the instances the shell publishes on window.__helexPlatform.
//
// Themes register SYNCHRONOUSLY, at module top level. @helex/state resolves the active theme when
// it is evaluated, so a theme registered after an `await platform.state()` is silently discarded.
// Anything that does need @helex/state belongs in the exported boot() below.

export const manifest = {
  "id": "akk",
  "name": "AKK",
  "description": "TEHIK's Andmekirjelduskeskkond — the Estonian health-data description environment.",
  "provides": [
    "theme"
  ],
  "themes": [
    "akk"
  ]
};

const platform = globalThis.window && window.__helexPlatform;

if (!platform || !platform.ui) {
  // Not fatal: the shell logs the failure and boots on its own palette. Saying which pack was
  // orphaned turns "the theme did not apply" into something diagnosable.
  console.warn('[pack:akk] window.__helexPlatform is unavailable — themes not registered');
} else {
  const ui = platform.ui;
  ui.registerTheme("akk", {
    "name": "AKK",
    "colorPrimary": "#007AAD",
    "colorPrimaryHover": "#006A97",
    "colorPrimaryLight": "#E5F2F8",
    "colorSecondary": "#5D6071",
    "colorSecondaryHover": "#4A4D5C",
    "colorAccent": "#00B649",
    "colorSidebar": "#34394C",
    "colorSidebarText": "#A0A2B8",
    "colorSidebarActive": "#007AAD",
    "colorSuccess": "#00B649",
    "colorWarning": "#78350F",
    "colorError": "#7F1D1D",
    "colorInfo": "#007AAD",
    "colorTextPrimary": "#5D6071",
    "colorTextSecondary": "#666A7D",
    "colorTextDisabled": "#9D9FB4",
    "colorBgPage": "#EDEFF1",
    "colorBgCard": "#FFFFFF",
    "colorBgHover": "#F2F3F3",
    "colorBorder": "#9D9FB4",
    "colorSuccessBg": "#EAF3EE",
    "colorSuccessBorder": "#308653",
    "colorWarningBg": "#FFF0CF",
    "colorWarningBorder": "#94690D",
    "colorErrorBg": "#FBECEC",
    "colorErrorBorder": "#D73E3E",
    "colorInfoBg": "#E7F0F6",
    "colorInfoBorder": "#005AA3",
    "fontFamily": "'Roboto', arial, helvetica, sans-serif",
    "fontSizeBase": 14,
    "borderRadiusSm": 0,
    "borderRadiusMd": 0,
    "borderRadiusLg": 0,
    "buttonRadius": 0,
    "buttonPaddingInline": 24,
    "controlHeight": 40,
    "controlHeightSM": 32,
    "controlHeightLG": 56,
    "controlBorderColor": "#838494",
    "tableHeaderBg": "#FAFAFA"
  });
}

/**
 * Anything needing @helex/state — a menu source, a slot contribution — goes here rather than above.
 * The shell awaits this after the module has evaluated, which is what makes the ordering above safe.
 */
export async function boot() {
  // This pack contributes themes only.
}
