// GENERATED by scripts/build-theme-packs.mjs — do not edit.
//
// A Helex extension pack: Evergreen, Slate and Wireframe — shipped with EMR until the catalogue existed.
//
// Loaded by the shell before first render via APP_BOOTSTRAP_MODULES (SHELL.11 R8). It imports
// nothing — a pack that imported @helex/ui would bundle a second React and antd, and two Reacts
// break hooks — and instead reads the instances the shell publishes on window.__helexPlatform.
//
// Themes register SYNCHRONOUSLY, at module top level. @helex/state resolves the active theme when
// it is evaluated, so a theme registered after an `await platform.state()` is silently discarded.
// Anything that does need @helex/state belongs in the exported boot() below.

export const manifest = {
  "id": "legacy",
  "name": "Classic Helex palettes",
  "description": "Evergreen, Slate and Wireframe — shipped with EMR until the catalogue existed.",
  "provides": [
    "theme"
  ],
  "themes": [
    "evergreen",
    "slate",
    "wireframe"
  ]
};

const platform = globalThis.window && window.__helexPlatform;

if (!platform || !platform.ui) {
  // Not fatal: the shell logs the failure and boots on its own palette. Saying which pack was
  // orphaned turns "the theme did not apply" into something diagnosable.
  console.warn('[pack:legacy] window.__helexPlatform is unavailable — themes not registered');
} else {
  const ui = platform.ui;
  ui.registerTheme("evergreen", {
    "name": "Evergreen",
    "colorPrimary": "#2D7A4F",
    "colorPrimaryHover": "#23603E",
    "colorPrimaryLight": "#E6F4EC",
    "colorSecondary": "#3A7CA5",
    "colorSecondaryHover": "#2E6384",
    "colorAccent": "#8B6E4E",
    "colorSidebar": "#1A3328",
    "colorSidebarText": "#C2D8CB",
    "colorSidebarActive": "#2D7A4F",
    "colorSuccess": "#43a047",
    "colorWarning": "#ff8f00",
    "colorError": "#c62828",
    "colorInfo": "#2D7A4F",
    "colorTextPrimary": "#1C2B22",
    "colorTextSecondary": "#4A5D52",
    "colorTextDisabled": "#94A39A",
    "colorBgPage": "#F4F8F5",
    "colorBgCard": "#FFFFFF",
    "colorBgHover": "#EDF3EF",
    "colorBorder": "#CDDAD2"
  });
  ui.registerTheme("slate", {
    "name": "Slate",
    "colorPrimary": "#455A75",
    "colorPrimaryHover": "#37485E",
    "colorPrimaryLight": "#ECEFF3",
    "colorSecondary": "#6B7A8F",
    "colorSecondaryHover": "#566374",
    "colorAccent": "#A0714B",
    "colorSidebar": "#2A3340",
    "colorSidebarText": "#C7CDD6",
    "colorSidebarActive": "#455A75",
    "colorSuccess": "#3E8E5A",
    "colorWarning": "#C4841D",
    "colorError": "#B0413E",
    "colorInfo": "#455A75",
    "colorTextPrimary": "#1F2733",
    "colorTextSecondary": "#4A5568",
    "colorTextDisabled": "#9AA3B0",
    "colorBgPage": "#F5F6F8",
    "colorBgCard": "#FFFFFF",
    "colorBgHover": "#ECEEF1",
    "colorBorder": "#CFD3DC"
  });
  ui.registerTheme("wireframe", {
    "name": "Wireframe",
    "colorPrimary": "#595959",
    "colorPrimaryHover": "#404040",
    "colorPrimaryLight": "#F0F0F0",
    "colorSecondary": "#8C8C8C",
    "colorSecondaryHover": "#737373",
    "colorAccent": "#A6A6A6",
    "colorSidebar": "#F5F5F5",
    "colorSidebarText": "#595959",
    "colorSidebarActive": "#404040",
    "colorSuccess": "#8C8C8C",
    "colorWarning": "#8C8C8C",
    "colorError": "#595959",
    "colorInfo": "#8C8C8C",
    "colorTextPrimary": "#262626",
    "colorTextSecondary": "#707070",
    "colorTextDisabled": "#BFBFBF",
    "colorBgPage": "#FAFAFA",
    "colorBgCard": "#FFFFFF",
    "colorBgHover": "#F0F0F0",
    "colorBorder": "#D9D9D9",
    "fontFamily": "'Inter', sans-serif"
  });
}

/**
 * Anything needing @helex/state — a menu source, a slot contribution — goes here rather than above.
 * The shell awaits this after the module has evaluated, which is what makes the ordering above safe.
 */
export async function boot() {
  // This pack contributes themes only.
}
