// GENERATED by scripts/build-theme-packs.mjs — do not edit.
//
// A Helex extension pack: Lietuvos medicinos biblioteka — the Lithuanian Health Sciences Library.
//
// Loaded by the shell before first render via APP_BOOTSTRAP_MODULES (SHELL.11 R8). It imports
// nothing — a pack that imported @helex/ui would bundle a second React and antd, and two Reacts
// break hooks — and instead reads the instances the shell publishes on window.__helexPlatform.
//
// Themes register SYNCHRONOUSLY, at module top level. @helex/state resolves the active theme when
// it is evaluated, so a theme registered after an `await platform.state()` is silently discarded.
// Anything that does need @helex/state belongs in the exported boot() below.

export const manifest = {
  "id": "lmb",
  "name": "LMB",
  "description": "Lietuvos medicinos biblioteka — the Lithuanian Health Sciences Library.",
  "provides": [
    "theme"
  ],
  "themes": [
    "lmb"
  ]
};

const platform = globalThis.window && window.__helexPlatform;

if (!platform || !platform.ui) {
  // Not fatal: the shell logs the failure and boots on its own palette. Saying which pack was
  // orphaned turns "the theme did not apply" into something diagnosable.
  console.warn('[pack:lmb] window.__helexPlatform is unavailable — themes not registered');
} else {
  const ui = platform.ui;
  ui.registerTheme("lmb", {
    "name": "LMB",
    "colorPrimary": "#0079BF",
    "colorPrimaryHover": "#0067A3",
    "colorPrimaryLight": "#E6F2F9",
    "colorSecondary": "#36373D",
    "colorSecondaryHover": "#303036",
    "colorAccent": "#DB1A03",
    "accentBar": [
      "#0079BF"
    ],
    "colorSidebar": "#0F2B47",
    "colorSidebarText": "#CBD5E1",
    "colorSidebarActive": "#1B6AB3",
    "colorSuccess": "#3cb6ab",
    "colorWarning": "#ff7d01",
    "colorError": "#DB1A03",
    "colorInfo": "#0079BF",
    "colorTextPrimary": "#36373D",
    "colorTextSecondary": "#6C6C6C",
    "colorTextDisabled": "#959595",
    "colorBgPage": "#EEEEEE",
    "colorBgCard": "#FFFFFF",
    "colorBgHover": "#F0F4F8",
    "colorBorder": "#DDDDDD",
    "borderRadiusSm": 4,
    "borderRadiusMd": 4,
    "borderRadiusLg": 4,
    "buttonRadius": 4
  });
}

/**
 * Anything needing @helex/state — a menu source, a slot contribution — goes here rather than above.
 * The shell awaits this after the module has evaluated, which is what makes the ordering above safe.
 */
export async function boot() {
  // This pack contributes themes only.
}
