// GENERATED by scripts/build-theme-packs.mjs — do not edit.
//
// A Helex extension pack: Helex, TEDI and Matrix — the three themes EMR ships with. Included for reference.
//
// Loaded by the shell before first render via APP_BOOTSTRAP_MODULES (SHELL.11 R8). It imports
// nothing — a pack that imported @helex/ui would bundle a second React and antd, and two Reacts
// break hooks — and instead reads the instances the shell publishes on window.__helexPlatform.
//
// Themes register SYNCHRONOUSLY, at module top level. @helex/state resolves the active theme when
// it is evaluated, so a theme registered after an `await platform.state()` is silently discarded.
// Anything that does need @helex/state belongs in the exported boot() below.

export const manifest = {
  "id": "platform",
  "name": "Helex platform themes",
  "description": "Helex, TEDI and Matrix — the three themes EMR ships with. Included for reference.",
  "provides": [
    "theme"
  ],
  "themes": [
    "helex",
    "tedi",
    "matrix"
  ]
};

const platform = globalThis.window && window.__helexPlatform;

if (!platform || !platform.ui) {
  // Not fatal: the shell logs the failure and boots on its own palette. Saying which pack was
  // orphaned turns "the theme did not apply" into something diagnosable.
  console.warn('[pack:platform] window.__helexPlatform is unavailable — themes not registered');
} else {
  const ui = platform.ui;
  ui.registerTheme("helex", {
    "name": "Helex",
    "accentBar": [
      "#3cb6ab",
      "#1B6AB3",
      "#ff7d01"
    ],
    "colorPrimary": "#1B6AB3",
    "colorPrimaryHover": "#15568F",
    "colorPrimaryLight": "#E8F2FB",
    "colorSecondary": "#2E7D6F",
    "colorSecondaryHover": "#236358",
    "colorAccent": "#6B5CA5",
    "colorSidebar": "#0F2B47",
    "colorSidebarText": "#CBD5E1",
    "colorSidebarActive": "#1B6AB3",
    "colorSuccess": "#3cb6ab",
    "colorWarning": "#ff7d01",
    "colorError": "#e74c3c",
    "colorInfo": "#1B6AB3",
    "colorTextPrimary": "#1A1A2E",
    "colorTextSecondary": "#4A5568",
    "colorTextDisabled": "#9CA3AF",
    "colorBgPage": "#F5F7FA",
    "colorBgCard": "#FFFFFF",
    "colorBgHover": "#F0F4F8",
    "colorBorder": "#D1D9E0",
    "controlBorderColor": "#8A8F98"
  });
  ui.registerTheme("tedi", {
    "name": "TEDI",
    "colorPrimary": "#005AA3",
    "colorPrimaryHover": "#004277",
    "colorPrimaryLight": "#E7F0F6",
    "colorSecondary": "#FF8000",
    "colorSecondaryHover": "#994D00",
    "colorAccent": "#4587BC",
    "colorSidebar": "#34394C",
    "colorSidebarText": "#FFFFFF",
    "colorSidebarActive": "#005AA3",
    "colorSuccess": "#308653",
    "colorWarning": "#94690D",
    "colorError": "#D73E3E",
    "colorInfo": "#005AA3",
    "colorTextPrimary": "#151926",
    "colorTextSecondary": "#4B4E62",
    "colorTextDisabled": "#9293A4",
    "colorBgPage": "#F9F9F9",
    "colorBgCard": "#FFFFFF",
    "colorBgHover": "#F0F0F2",
    "colorBorder": "#E1E2E5",
    "colorSuccessBg": "#EAF3EE",
    "colorSuccessBorder": "#308653",
    "colorWarningBg": "#FFF0CF",
    "colorWarningBorder": "#94690D",
    "colorErrorBg": "#FBECEC",
    "colorErrorBorder": "#D73E3E",
    "colorInfoBg": "#E7F0F6",
    "colorInfoBorder": "#005AA3",
    "fontFamily": "'Roboto', arial, helvetica, sans-serif",
    "fontSizeBase": 16,
    "borderRadiusSm": 4,
    "borderRadiusMd": 4,
    "borderRadiusLg": 4,
    "buttonRadius": 48,
    "buttonPaddingInline": 24,
    "controlHeight": 40,
    "controlHeightSM": 32,
    "controlHeightLG": 56,
    "controlBorderColor": "#838494",
    "tableHeaderBg": "#FFFFFF",
    "spacing": {
      "pagePadding": {
        "comfortable": 32,
        "default": 24,
        "compact": 16,
        "tiny": 12
      },
      "tableCell": {
        "comfortable": {
          "block": 14,
          "inline": 16,
          "editRow": 64
        },
        "default": {
          "block": 12,
          "inline": 14,
          "editRow": 48
        },
        "compact": {
          "block": 8,
          "inline": 10,
          "editRow": 40
        },
        "tiny": {
          "block": 4,
          "inline": 8,
          "editRow": 38
        }
      }
    }
  });
  ui.registerTheme("matrix", {
    "name": "Matrix",
    "algorithm": "dark",
    "colorPrimary": "#00FF41",
    "colorPrimaryHover": "#5BF08A",
    "colorPrimaryLight": "#163A16",
    "colorTextOnPrimary": "#08110A",
    "colorSecondary": "#3DDC84",
    "colorSecondaryHover": "#2BD46B",
    "colorAccent": "#5BE0C8",
    "colorSidebar": "#040A04",
    "colorSidebarText": "#6EC86E",
    "colorSidebarActive": "#00FF41",
    "colorSuccess": "#3DDC84",
    "colorWarning": "#FFC857",
    "colorError": "#FF5C5C",
    "colorInfo": "#5BE0C8",
    "colorTextPrimary": "#99F699",
    "colorTextSecondary": "#6EC86E",
    "colorTextDisabled": "#438543",
    "colorBgPage": "#060E06",
    "colorBgCard": "#0C1F0C",
    "colorBgHover": "#112A11",
    "colorBgElevated": "#143314",
    "colorBorder": "#193E19",
    "controlBorderColor": "#3F8D3F"
  });
}

/**
 * Anything needing @helex/state — a menu source, a slot contribution — goes here rather than above.
 * The shell awaits this after the module has evaluated, which is what makes the ordering above safe.
 */
export async function boot() {
  // This pack contributes themes only.
}
