// GENERATED by scripts/build-theme-packs.mjs — do not edit.
//
// A Helex extension pack: Tallinn University of Technology, from the published TalTech design system.
//
// Loaded by the shell before first render via APP_BOOTSTRAP_MODULES (SHELL.11 R8). It imports
// nothing — a pack that imported @helex/ui would bundle a second React and antd, and two Reacts
// break hooks — and instead reads the instances the shell publishes on window.__helexPlatform.
//
// Themes register SYNCHRONOUSLY, at module top level. @helex/state resolves the active theme when
// it is evaluated, so a theme registered after an `await platform.state()` is silently discarded.
// Anything that does need @helex/state belongs in the exported boot() below.

export const manifest = {
  "id": "taltech",
  "name": "TalTech",
  "description": "Tallinn University of Technology, from the published TalTech design system.",
  "provides": [
    "theme"
  ],
  "themes": [
    "taltech"
  ]
};

const platform = globalThis.window && window.__helexPlatform;

if (!platform || !platform.ui) {
  // Not fatal: the shell logs the failure and boots on its own palette. Saying which pack was
  // orphaned turns "the theme did not apply" into something diagnosable.
  console.warn('[pack:taltech] window.__helexPlatform is unavailable — themes not registered');
} else {
  const ui = platform.ui;
  ui.registerTheme("taltech", {
    "name": "TalTech",
    "colorPrimary": "#342b60",
    "colorPrimaryHover": "#272048",
    "colorPrimaryLight": "#ebeaef",
    "colorSecondary": "#e4067e",
    "colorSecondaryHover": "#ab055f",
    "colorAccent": "#4dbed2",
    "accentBar": [
      "#e4067e",
      "#aa1352",
      "#342b60"
    ],
    "colorSidebar": "#342b60",
    "colorSidebarText": "#cccad7",
    "colorSidebarActive": "#e4067e",
    "colorSuccess": "#277257",
    "colorWarning": "#80642d",
    "colorError": "#af4458",
    "colorInfo": "#2468b0",
    "colorTextPrimary": "#25262c",
    "colorTextSecondary": "#4a4b58",
    "colorTextDisabled": "#9396b0",
    "colorBgPage": "#f6f6f8",
    "colorBgCard": "#ffffff",
    "colorBgHover": "#ededf2",
    "colorBorder": "#ededf2",
    "controlBorderColor": "#6e7184",
    "fontFamily": "'Proxima Nova', Verdana, system-ui, sans-serif",
    "borderRadiusSm": 2,
    "borderRadiusMd": 4,
    "borderRadiusLg": 8
  });
}

/**
 * Anything needing @helex/state — a menu source, a slot contribution — goes here rather than above.
 * The shell awaits this after the module has evaluated, which is what makes the ordering above safe.
 */
export async function boot() {
  // This pack contributes themes only.
}
