// GENERATED by scripts/build-theme-packs.mjs — do not edit.
//
// A Helex extension pack: The Estonian Health Insurance Fund, from their published stiiliraamat 2026.
//
// Loaded by the shell before first render via APP_BOOTSTRAP_MODULES (SHELL.11 R8). It imports
// nothing — a pack that imported @helex/ui would bundle a second React and antd, and two Reacts
// break hooks — and instead reads the instances the shell publishes on window.__helexPlatform.
//
// Themes register SYNCHRONOUSLY, at module top level. @helex/state resolves the active theme when
// it is evaluated, so a theme registered after an `await platform.state()` is silently discarded.
// Anything that does need @helex/state belongs in the exported boot() below.

export const manifest = {
  "id": "tervisekassa",
  "name": "Tervisekassa",
  "description": "The Estonian Health Insurance Fund, from their published stiiliraamat 2026.",
  "provides": [
    "theme"
  ],
  "themes": [
    "tervisekassa"
  ]
};

const platform = globalThis.window && window.__helexPlatform;

if (!platform || !platform.ui) {
  // Not fatal: the shell logs the failure and boots on its own palette. Saying which pack was
  // orphaned turns "the theme did not apply" into something diagnosable.
  console.warn('[pack:tervisekassa] window.__helexPlatform is unavailable — themes not registered');
} else {
  const ui = platform.ui;
  ui.registerTheme("tervisekassa", {
    "name": "Tervisekassa",
    "colorPrimary": "#105B9E",
    "colorPrimaryHover": "#094A85",
    "colorPrimaryLight": "#E0E9F1",
    "colorSecondary": "#A03170",
    "colorSecondaryHover": "#7E2659",
    "colorAccent": "#E882B3",
    "accentBar": [
      "#073A67",
      "#105B9E",
      "#A03170"
    ],
    "colorSidebar": "#073A67",
    "colorSidebarText": "#85A9C9",
    "colorSidebarActive": "#F8C8DC",
    "colorSuccess": "#1F7A54",
    "colorWarning": "#8A5A16",
    "colorError": "#B3261E",
    "colorInfo": "#105B9E",
    "colorTextPrimary": "#1D1D1B",
    "colorTextSecondary": "#55606B",
    "colorTextDisabled": "#8E99A3",
    "colorBgPage": "#F5F8FB",
    "colorBgCard": "#FFFFFF",
    "colorBgHover": "#E0E9F1",
    "colorBorder": "#C8D4E0",
    "controlBorderColor": "#6E7C8A",
    "colorSuccessBg": "#E9F3EE",
    "colorSuccessBorder": "#1F7A54",
    "colorWarningBg": "#FBF1E2",
    "colorWarningBorder": "#8A5A16",
    "colorErrorBg": "#FBEBEA",
    "colorErrorBorder": "#B3261E",
    "colorInfoBg": "#E0E9F1",
    "colorInfoBorder": "#105B9E",
    "fontFamily": "'Noto Sans', Arial, 'Helvetica Neue', helvetica, sans-serif",
    "fontSizeBase": 14,
    "borderRadiusSm": 2,
    "borderRadiusMd": 4,
    "borderRadiusLg": 8
  });
}

/**
 * Anything needing @helex/state — a menu source, a slot contribution — goes here rather than above.
 * The shell awaits this after the module has evaluated, which is what makes the ordering above safe.
 */
export async function boot() {
  // This pack contributes themes only.
}
